# @see https://github.com/just-the-docs/just-the-docs/blob/main/_config.yml
title: shell-var-lint
description: shell-var-lint documentation
theme: just-the-docs
repository: AlexSkrypnyk/shell-var-lint
url: https://getshell-var-lint.dev

layout: default

logo: "/assets/logo.png"

# Aux links for the upper right navigation.
aux_links:
  "shell-var-lint on GitHub":
    - "//github.com/AlexSkrypnyk/shell-var-lint"
aux_links_new_tab: true

# Print the latest version of the project in the upper right navigation.
# Set to false to disable.
# Relies on jekyll-github-metadata plugin.
# @see https://github.com/jekyll/github-metadata/blob/main/docs/authentication.md
aux_links_latest_version_text: "v"
# Link to the latest version zipball. If false - link to the latest release page.
aux_links_latest_version_link_zipball: true

back_to_top: true
back_to_top_text: "Back to top"

enable_copy_code_button: true

heading_anchors: true

footer_content: "Copyright &copy;2023 <a href=\"mailto:alex@drevops.com\">AlexSkrypnyk</a>"

# Footer "Edit this page on GitHub" link text.
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/AlexSkrypnyk/shell-var-lint"
gh_edit_branch: "main"
gh_edit_source: docs
gh_edit_view_mode: "tree"

# Google Analytics Tracking (optional)
# Supports a CSV of tracking ID strings (eg. "UA-1234567-89,G-1AB234CDE5")
# ga_tracking: G-
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

plugins:
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll_include_plugin
  - jekyll-github-metadata
