name: Test

on:
  pull_request:
    branches:
      - main
      - 'feature/**'
  push:
    branches:
      - main
      - 'feature/**'

jobs:
  test-php:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: /tmp/composer-cache
        key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
    - uses: php-actions/composer@v6
    - run: composer lint || true
    - run: composer test
    - uses: paambaati/codeclimate-action@v5.0.0
      env:
        CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
      with:
        coverageCommand: composer test:coverage
        coverageLocations: |
          ${{github.workspace}}/.coverage-cobertura.xml:cobertura
    - uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: .coverage-html
